### PR TITLE
Thread safe

### PR DESCRIPTION
**Pull request by DragonSA**
The main focus of this branch is to ensure thread safety of ESI.NET.  The use of `DefaultHeaders` instead of `HttpRequestMessage.Headers` was causing concurrency issues when the headers were modified simultaneously from different threads.  

I also:
- Updates the supported .NET versions
- Ensured HttpResponseMessage was disposed in EsiResponse's ctor.

### CODE REVIEW

**Comment by seraphx2** [comment]
Sorry. Getting on this today. Time flies. lol. ended up forgetting this was here.
I'll test this and then merge if all goes well.
And thanks for the .net updates. I actually had a branch with that same change, so I'll just take yours. :p

**Comment by Ablecken** [comment]
Hey there, just wondering if you are still working on getting this in? I want to use it but need/want it to be threadsafe. No worries if not, just wanted a timeline on if I should use the fork and build it or wait for a merge and use the nuget package.

**Comment by seraphx2** [comment]
blah. forgot to finish this up. let me double check everything and i should have a build out in just a little bit today. sorry about that

**Review by seraphx2 — APPROVED** [review]

**Comment by seraphx2** [comment]
All is good to go. After having not deployed for a year, some tokens, auth, and unsupported versions in tasks were all broken or off  lol.

**Comment by Ablecken** [comment]
Awesome, thanks a ton

**Comment by DragonSA** [comment]
It's a pleasure.  Glad to be of help.

**Pull request merged**
